/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TokenPresale {
  export type StageStruct = {
    price: BigNumberish;
    offeredAmount: BigNumberish;
    soldAmount: BigNumberish;
    minBuyTokens: BigNumberish;
    maxBuyTokens: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    cliff: BigNumberish;
    duration: BigNumberish;
    releaseInterval: BigNumberish;
    whitelistOnly: boolean;
  };

  export type StageStructOutput = [
    price: bigint,
    offeredAmount: bigint,
    soldAmount: bigint,
    minBuyTokens: bigint,
    maxBuyTokens: bigint,
    startTime: bigint,
    endTime: bigint,
    cliff: bigint,
    duration: bigint,
    releaseInterval: bigint,
    whitelistOnly: boolean
  ] & {
    price: bigint;
    offeredAmount: bigint;
    soldAmount: bigint;
    minBuyTokens: bigint;
    maxBuyTokens: bigint;
    startTime: bigint;
    endTime: bigint;
    cliff: bigint;
    duration: bigint;
    releaseInterval: bigint;
    whitelistOnly: boolean;
  };
}

export interface TokenPresaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addStage"
      | "adminAddPurchase"
      | "buyWithETH"
      | "buyWithToken"
      | "buyerPurchased"
      | "buyerPurchasedForStage"
      | "calculateTokenAmount"
      | "canUserClaim"
      | "claim"
      | "claimEnabled"
      | "claimableAmount"
      | "currentStage"
      | "depositSaleTokens"
      | "emergencyMode"
      | "emergencyWithdraw"
      | "enableEmergencyMode"
      | "ethUsdPriceFeed"
      | "getClaimStatus"
      | "getEthPrice"
      | "getRemainingLimit"
      | "getStage"
      | "getVestingSchedule"
      | "getVestingSchedulesCount"
      | "globalClaimStartTime"
      | "owner"
      | "pause"
      | "paused"
      | "paymentAllowed"
      | "paymentDecimals"
      | "recoverToken"
      | "renounceOwnership"
      | "saleToken"
      | "saleTokenDecimals"
      | "saleTokenSet"
      | "setClaimEnabled"
      | "setEthPriceFeed"
      | "setGlobalClaimStartTime"
      | "setPaymentToken"
      | "setSaleToken"
      | "setTreasury"
      | "setWhitelist"
      | "stages"
      | "stagesCount"
      | "totalAllocated"
      | "totalClaimed"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "updateStage"
      | "vestedAmount"
      | "vestingSchedules"
      | "whitelist"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Bought"
      | "ClaimDisabled"
      | "ClaimEnabled"
      | "Claimed"
      | "EmergencyModeEnabled"
      | "EmergencyWithdraw"
      | "EthPriceFeedSet"
      | "EthReceived"
      | "GlobalClaimStartTimeSet"
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentTokenToggled"
      | "SaleTokenSet"
      | "StageAdded"
      | "StageUpdated"
      | "TreasurySet"
      | "Unpaused"
      | "VestingScheduleCreated"
      | "WhitelistUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addStage",
    values: [TokenPresale.StageStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "adminAddPurchase",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyWithETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyWithToken",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyerPurchased",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyerPurchasedForStage",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTokenAmount",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canUserClaim",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimableAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentStage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositSaleTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enableEmergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ethUsdPriceFeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEthPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingLimit",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingSchedule",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingSchedulesCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalClaimStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentDecimals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "saleToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "saleTokenDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "saleTokenSet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setEthPriceFeed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalClaimStartTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentToken",
    values: [AddressLike, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSaleToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelist",
    values: [BigNumberish, AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "stages",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stagesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAllocated",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalClaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateStage",
    values: [BigNumberish, TokenPresale.StageStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "vestedAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingSchedules",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addStage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adminAddPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyWithETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyWithToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyerPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyerPurchasedForStage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTokenAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canUserClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentStage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositSaleTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableEmergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethUsdPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEthPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingSchedulesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalClaimStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "saleToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "saleTokenDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "saleTokenSet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEthPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalClaimStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSaleToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stages", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stagesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAllocated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateStage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingSchedules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace BoughtEvent {
  export type InputTuple = [
    buyer: AddressLike,
    paymentToken: AddressLike,
    paymentAmount: BigNumberish,
    tokenAmount: BigNumberish,
    stageId: BigNumberish,
    usdValue: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    paymentToken: string,
    paymentAmount: bigint,
    tokenAmount: bigint,
    stageId: bigint,
    usdValue: bigint
  ];
  export interface OutputObject {
    buyer: string;
    paymentToken: string;
    paymentAmount: bigint;
    tokenAmount: bigint;
    stageId: bigint;
    usdValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimDisabledEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimEnabledEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    amount: BigNumberish,
    schedulesClaimed: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    amount: bigint,
    schedulesClaimed: bigint
  ];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
    schedulesClaimed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyModeEnabledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [buyer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [buyer: string, amount: bigint];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EthPriceFeedSetEvent {
  export type InputTuple = [feed: AddressLike];
  export type OutputTuple = [feed: string];
  export interface OutputObject {
    feed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EthReceivedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalClaimStartTimeSetEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentTokenToggledEvent {
  export type InputTuple = [token: AddressLike, allowed: boolean];
  export type OutputTuple = [token: string, allowed: boolean];
  export interface OutputObject {
    token: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleTokenSetEvent {
  export type InputTuple = [token: AddressLike, decimals: BigNumberish];
  export type OutputTuple = [token: string, decimals: bigint];
  export interface OutputObject {
    token: string;
    decimals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StageAddedEvent {
  export type InputTuple = [stageId: BigNumberish];
  export type OutputTuple = [stageId: bigint];
  export interface OutputObject {
    stageId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StageUpdatedEvent {
  export type InputTuple = [stageId: BigNumberish];
  export type OutputTuple = [stageId: bigint];
  export interface OutputObject {
    stageId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasurySetEvent {
  export type InputTuple = [treasury: AddressLike];
  export type OutputTuple = [treasury: string];
  export interface OutputObject {
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingScheduleCreatedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    scheduleId: BigNumberish,
    amount: BigNumberish,
    startTime: BigNumberish,
    cliff: BigNumberish,
    duration: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    scheduleId: bigint,
    amount: bigint,
    startTime: bigint,
    cliff: bigint,
    duration: bigint
  ];
  export interface OutputObject {
    buyer: string;
    scheduleId: bigint;
    amount: bigint;
    startTime: bigint;
    cliff: bigint;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistUpdatedEvent {
  export type InputTuple = [
    stageId: BigNumberish,
    account: AddressLike,
    allowed: boolean
  ];
  export type OutputTuple = [
    stageId: bigint,
    account: string,
    allowed: boolean
  ];
  export interface OutputObject {
    stageId: bigint;
    account: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenPresale extends BaseContract {
  connect(runner?: ContractRunner | null): TokenPresale;
  waitForDeployment(): Promise<this>;

  interface: TokenPresaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addStage: TypedContractMethod<
    [stage: TokenPresale.StageStruct],
    [void],
    "nonpayable"
  >;

  adminAddPurchase: TypedContractMethod<
    [buyer: AddressLike, stageId: BigNumberish, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  buyWithETH: TypedContractMethod<
    [minExpectedTokens: BigNumberish],
    [void],
    "payable"
  >;

  buyWithToken: TypedContractMethod<
    [
      paymentToken: AddressLike,
      paymentAmount: BigNumberish,
      minExpectedTokens: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  buyerPurchased: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  buyerPurchasedForStage: TypedContractMethod<
    [stageId: BigNumberish, buyer: AddressLike],
    [bigint],
    "view"
  >;

  calculateTokenAmount: TypedContractMethod<
    [
      stageId: BigNumberish,
      paymentToken: AddressLike,
      paymentAmount: BigNumberish
    ],
    [[bigint, bigint] & { tokenAmount: bigint; usdValue: bigint }],
    "view"
  >;

  canUserClaim: TypedContractMethod<
    [account: AddressLike],
    [
      [boolean, bigint, string] & {
        canClaim: boolean;
        claimable: bigint;
        reason: string;
      }
    ],
    "view"
  >;

  claim: TypedContractMethod<[], [void], "nonpayable">;

  claimEnabled: TypedContractMethod<[], [boolean], "view">;

  claimableAmount: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  currentStage: TypedContractMethod<
    [],
    [
      [bigint, TokenPresale.StageStructOutput] & {
        stageId: bigint;
        s: TokenPresale.StageStructOutput;
      }
    ],
    "view"
  >;

  depositSaleTokens: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyMode: TypedContractMethod<[], [boolean], "view">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  enableEmergencyMode: TypedContractMethod<[], [void], "nonpayable">;

  ethUsdPriceFeed: TypedContractMethod<[], [string], "view">;

  getClaimStatus: TypedContractMethod<
    [],
    [
      [boolean, bigint, boolean] & {
        enabled: boolean;
        startTime: bigint;
        canClaimNow: boolean;
      }
    ],
    "view"
  >;

  getEthPrice: TypedContractMethod<
    [],
    [[bigint, bigint] & { price: bigint; decimals: bigint }],
    "view"
  >;

  getRemainingLimit: TypedContractMethod<
    [stageId: BigNumberish, buyer: AddressLike],
    [bigint],
    "view"
  >;

  getStage: TypedContractMethod<
    [id: BigNumberish],
    [TokenPresale.StageStructOutput],
    "view"
  >;

  getVestingSchedule: TypedContractMethod<
    [account: AddressLike, scheduleIndex: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalAmount: bigint;
        claimed: bigint;
        vested: bigint;
        claimable: bigint;
        startTime: bigint;
        cliff: bigint;
        duration: bigint;
        releaseInterval: bigint;
      }
    ],
    "view"
  >;

  getVestingSchedulesCount: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  globalClaimStartTime: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymentAllowed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  paymentDecimals: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  recoverToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  saleToken: TypedContractMethod<[], [string], "view">;

  saleTokenDecimals: TypedContractMethod<[], [bigint], "view">;

  saleTokenSet: TypedContractMethod<[], [boolean], "view">;

  setClaimEnabled: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  setEthPriceFeed: TypedContractMethod<
    [feed: AddressLike],
    [void],
    "nonpayable"
  >;

  setGlobalClaimStartTime: TypedContractMethod<
    [_startTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPaymentToken: TypedContractMethod<
    [token: AddressLike, allowed: boolean, decimals: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSaleToken: TypedContractMethod<
    [_saleToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setWhitelist: TypedContractMethod<
    [stageId: BigNumberish, accounts: AddressLike[], allowed: boolean],
    [void],
    "nonpayable"
  >;

  stages: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        price: bigint;
        offeredAmount: bigint;
        soldAmount: bigint;
        minBuyTokens: bigint;
        maxBuyTokens: bigint;
        startTime: bigint;
        endTime: bigint;
        cliff: bigint;
        duration: bigint;
        releaseInterval: bigint;
        whitelistOnly: boolean;
      }
    ],
    "view"
  >;

  stagesCount: TypedContractMethod<[], [bigint], "view">;

  totalAllocated: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalClaimed: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateStage: TypedContractMethod<
    [id: BigNumberish, data: TokenPresale.StageStruct],
    [void],
    "nonpayable"
  >;

  vestedAmount: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  vestingSchedules: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalAmount: bigint;
        claimed: bigint;
        startTime: bigint;
        cliff: bigint;
        duration: bigint;
        releaseInterval: bigint;
      }
    ],
    "view"
  >;

  whitelist: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  withdrawFunds: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addStage"
  ): TypedContractMethod<
    [stage: TokenPresale.StageStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "adminAddPurchase"
  ): TypedContractMethod<
    [buyer: AddressLike, stageId: BigNumberish, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyWithETH"
  ): TypedContractMethod<[minExpectedTokens: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "buyWithToken"
  ): TypedContractMethod<
    [
      paymentToken: AddressLike,
      paymentAmount: BigNumberish,
      minExpectedTokens: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyerPurchased"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "buyerPurchasedForStage"
  ): TypedContractMethod<
    [stageId: BigNumberish, buyer: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateTokenAmount"
  ): TypedContractMethod<
    [
      stageId: BigNumberish,
      paymentToken: AddressLike,
      paymentAmount: BigNumberish
    ],
    [[bigint, bigint] & { tokenAmount: bigint; usdValue: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "canUserClaim"
  ): TypedContractMethod<
    [account: AddressLike],
    [
      [boolean, bigint, string] & {
        canClaim: boolean;
        claimable: bigint;
        reason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimableAmount"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentStage"
  ): TypedContractMethod<
    [],
    [
      [bigint, TokenPresale.StageStructOutput] & {
        stageId: bigint;
        s: TokenPresale.StageStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositSaleTokens"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enableEmergencyMode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ethUsdPriceFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getClaimStatus"
  ): TypedContractMethod<
    [],
    [
      [boolean, bigint, boolean] & {
        enabled: boolean;
        startTime: bigint;
        canClaimNow: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEthPrice"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { price: bigint; decimals: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemainingLimit"
  ): TypedContractMethod<
    [stageId: BigNumberish, buyer: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStage"
  ): TypedContractMethod<
    [id: BigNumberish],
    [TokenPresale.StageStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVestingSchedule"
  ): TypedContractMethod<
    [account: AddressLike, scheduleIndex: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalAmount: bigint;
        claimed: bigint;
        vested: bigint;
        claimable: bigint;
        startTime: bigint;
        cliff: bigint;
        duration: bigint;
        releaseInterval: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVestingSchedulesCount"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "globalClaimStartTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentAllowed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentDecimals"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "recoverToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "saleToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "saleTokenDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "saleTokenSet"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setClaimEnabled"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEthPriceFeed"
  ): TypedContractMethod<[feed: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGlobalClaimStartTime"
  ): TypedContractMethod<[_startTime: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaymentToken"
  ): TypedContractMethod<
    [token: AddressLike, allowed: boolean, decimals: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSaleToken"
  ): TypedContractMethod<[_saleToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWhitelist"
  ): TypedContractMethod<
    [stageId: BigNumberish, accounts: AddressLike[], allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stages"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        price: bigint;
        offeredAmount: bigint;
        soldAmount: bigint;
        minBuyTokens: bigint;
        maxBuyTokens: bigint;
        startTime: bigint;
        endTime: bigint;
        cliff: bigint;
        duration: bigint;
        releaseInterval: bigint;
        whitelistOnly: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "stagesCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalAllocated"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalClaimed"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateStage"
  ): TypedContractMethod<
    [id: BigNumberish, data: TokenPresale.StageStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vestedAmount"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "vestingSchedules"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalAmount: bigint;
        claimed: bigint;
        startTime: bigint;
        cliff: bigint;
        duration: bigint;
        releaseInterval: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Bought"
  ): TypedContractEvent<
    BoughtEvent.InputTuple,
    BoughtEvent.OutputTuple,
    BoughtEvent.OutputObject
  >;
  getEvent(
    key: "ClaimDisabled"
  ): TypedContractEvent<
    ClaimDisabledEvent.InputTuple,
    ClaimDisabledEvent.OutputTuple,
    ClaimDisabledEvent.OutputObject
  >;
  getEvent(
    key: "ClaimEnabled"
  ): TypedContractEvent<
    ClaimEnabledEvent.InputTuple,
    ClaimEnabledEvent.OutputTuple,
    ClaimEnabledEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyModeEnabled"
  ): TypedContractEvent<
    EmergencyModeEnabledEvent.InputTuple,
    EmergencyModeEnabledEvent.OutputTuple,
    EmergencyModeEnabledEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "EthPriceFeedSet"
  ): TypedContractEvent<
    EthPriceFeedSetEvent.InputTuple,
    EthPriceFeedSetEvent.OutputTuple,
    EthPriceFeedSetEvent.OutputObject
  >;
  getEvent(
    key: "EthReceived"
  ): TypedContractEvent<
    EthReceivedEvent.InputTuple,
    EthReceivedEvent.OutputTuple,
    EthReceivedEvent.OutputObject
  >;
  getEvent(
    key: "GlobalClaimStartTimeSet"
  ): TypedContractEvent<
    GlobalClaimStartTimeSetEvent.InputTuple,
    GlobalClaimStartTimeSetEvent.OutputTuple,
    GlobalClaimStartTimeSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentTokenToggled"
  ): TypedContractEvent<
    PaymentTokenToggledEvent.InputTuple,
    PaymentTokenToggledEvent.OutputTuple,
    PaymentTokenToggledEvent.OutputObject
  >;
  getEvent(
    key: "SaleTokenSet"
  ): TypedContractEvent<
    SaleTokenSetEvent.InputTuple,
    SaleTokenSetEvent.OutputTuple,
    SaleTokenSetEvent.OutputObject
  >;
  getEvent(
    key: "StageAdded"
  ): TypedContractEvent<
    StageAddedEvent.InputTuple,
    StageAddedEvent.OutputTuple,
    StageAddedEvent.OutputObject
  >;
  getEvent(
    key: "StageUpdated"
  ): TypedContractEvent<
    StageUpdatedEvent.InputTuple,
    StageUpdatedEvent.OutputTuple,
    StageUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TreasurySet"
  ): TypedContractEvent<
    TreasurySetEvent.InputTuple,
    TreasurySetEvent.OutputTuple,
    TreasurySetEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VestingScheduleCreated"
  ): TypedContractEvent<
    VestingScheduleCreatedEvent.InputTuple,
    VestingScheduleCreatedEvent.OutputTuple,
    VestingScheduleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistUpdated"
  ): TypedContractEvent<
    WhitelistUpdatedEvent.InputTuple,
    WhitelistUpdatedEvent.OutputTuple,
    WhitelistUpdatedEvent.OutputObject
  >;

  filters: {
    "Bought(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      BoughtEvent.InputTuple,
      BoughtEvent.OutputTuple,
      BoughtEvent.OutputObject
    >;
    Bought: TypedContractEvent<
      BoughtEvent.InputTuple,
      BoughtEvent.OutputTuple,
      BoughtEvent.OutputObject
    >;

    "ClaimDisabled(uint256)": TypedContractEvent<
      ClaimDisabledEvent.InputTuple,
      ClaimDisabledEvent.OutputTuple,
      ClaimDisabledEvent.OutputObject
    >;
    ClaimDisabled: TypedContractEvent<
      ClaimDisabledEvent.InputTuple,
      ClaimDisabledEvent.OutputTuple,
      ClaimDisabledEvent.OutputObject
    >;

    "ClaimEnabled(uint256)": TypedContractEvent<
      ClaimEnabledEvent.InputTuple,
      ClaimEnabledEvent.OutputTuple,
      ClaimEnabledEvent.OutputObject
    >;
    ClaimEnabled: TypedContractEvent<
      ClaimEnabledEvent.InputTuple,
      ClaimEnabledEvent.OutputTuple,
      ClaimEnabledEvent.OutputObject
    >;

    "Claimed(address,uint256,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "EmergencyModeEnabled()": TypedContractEvent<
      EmergencyModeEnabledEvent.InputTuple,
      EmergencyModeEnabledEvent.OutputTuple,
      EmergencyModeEnabledEvent.OutputObject
    >;
    EmergencyModeEnabled: TypedContractEvent<
      EmergencyModeEnabledEvent.InputTuple,
      EmergencyModeEnabledEvent.OutputTuple,
      EmergencyModeEnabledEvent.OutputObject
    >;

    "EmergencyWithdraw(address,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "EthPriceFeedSet(address)": TypedContractEvent<
      EthPriceFeedSetEvent.InputTuple,
      EthPriceFeedSetEvent.OutputTuple,
      EthPriceFeedSetEvent.OutputObject
    >;
    EthPriceFeedSet: TypedContractEvent<
      EthPriceFeedSetEvent.InputTuple,
      EthPriceFeedSetEvent.OutputTuple,
      EthPriceFeedSetEvent.OutputObject
    >;

    "EthReceived(address,uint256)": TypedContractEvent<
      EthReceivedEvent.InputTuple,
      EthReceivedEvent.OutputTuple,
      EthReceivedEvent.OutputObject
    >;
    EthReceived: TypedContractEvent<
      EthReceivedEvent.InputTuple,
      EthReceivedEvent.OutputTuple,
      EthReceivedEvent.OutputObject
    >;

    "GlobalClaimStartTimeSet(uint256)": TypedContractEvent<
      GlobalClaimStartTimeSetEvent.InputTuple,
      GlobalClaimStartTimeSetEvent.OutputTuple,
      GlobalClaimStartTimeSetEvent.OutputObject
    >;
    GlobalClaimStartTimeSet: TypedContractEvent<
      GlobalClaimStartTimeSetEvent.InputTuple,
      GlobalClaimStartTimeSetEvent.OutputTuple,
      GlobalClaimStartTimeSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentTokenToggled(address,bool)": TypedContractEvent<
      PaymentTokenToggledEvent.InputTuple,
      PaymentTokenToggledEvent.OutputTuple,
      PaymentTokenToggledEvent.OutputObject
    >;
    PaymentTokenToggled: TypedContractEvent<
      PaymentTokenToggledEvent.InputTuple,
      PaymentTokenToggledEvent.OutputTuple,
      PaymentTokenToggledEvent.OutputObject
    >;

    "SaleTokenSet(address,uint8)": TypedContractEvent<
      SaleTokenSetEvent.InputTuple,
      SaleTokenSetEvent.OutputTuple,
      SaleTokenSetEvent.OutputObject
    >;
    SaleTokenSet: TypedContractEvent<
      SaleTokenSetEvent.InputTuple,
      SaleTokenSetEvent.OutputTuple,
      SaleTokenSetEvent.OutputObject
    >;

    "StageAdded(uint256)": TypedContractEvent<
      StageAddedEvent.InputTuple,
      StageAddedEvent.OutputTuple,
      StageAddedEvent.OutputObject
    >;
    StageAdded: TypedContractEvent<
      StageAddedEvent.InputTuple,
      StageAddedEvent.OutputTuple,
      StageAddedEvent.OutputObject
    >;

    "StageUpdated(uint256)": TypedContractEvent<
      StageUpdatedEvent.InputTuple,
      StageUpdatedEvent.OutputTuple,
      StageUpdatedEvent.OutputObject
    >;
    StageUpdated: TypedContractEvent<
      StageUpdatedEvent.InputTuple,
      StageUpdatedEvent.OutputTuple,
      StageUpdatedEvent.OutputObject
    >;

    "TreasurySet(address)": TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;
    TreasurySet: TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VestingScheduleCreated(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      VestingScheduleCreatedEvent.InputTuple,
      VestingScheduleCreatedEvent.OutputTuple,
      VestingScheduleCreatedEvent.OutputObject
    >;
    VestingScheduleCreated: TypedContractEvent<
      VestingScheduleCreatedEvent.InputTuple,
      VestingScheduleCreatedEvent.OutputTuple,
      VestingScheduleCreatedEvent.OutputObject
    >;

    "WhitelistUpdated(uint256,address,bool)": TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
    WhitelistUpdated: TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
  };
}
